services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=financialmanagement'
      - 'POSTGRES_PASSWORD=abc12345'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
